version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '127.0.0.1:5173:5173'

    volumes:
      - .:/app/sigl_front

    command: sh -c "npm install && npm run dev"
